In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\nithi\Downloads\data10.csv")

In [26]:
df

    feature1  feature2  class
0  -2.368256  0.605615      0
1  -2.460313  1.729759      0
2   1.292390 -2.291875      1
3  -3.780303 -1.534776      0
4   3.297534  1.185131      1
..       ...       ...    ...
95 -1.699185  2.220762      0
96  1.037832  2.521379      1
97  2.701200 -1.616977      1
98 -2.438428 -0.997694      0
99  1.523677 -1.762128      1

[100 rows x 3 columns]

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   feature1  100 non-null    float64
 1   feature2  100 non-null    float64
 2   class     100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [28]:
for column in df.columns:
    print(f"Column: {column}")
    print(df[column].value_counts())
    print("\n")

feature1
-2.368256    1
-1.845582    1
 1.982998    1
-2.008271    1
-2.188743    1
            ..
-1.689672    1
 2.322464    1
 2.422925    1
-1.630397    1
 1.523677    1
Name: count, Length: 100, dtype: int64


feature2
 0.605615    1
-1.627897    1
 1.735513    1
 1.255796    1
-2.767420    1
            ..
 0.834247    1
 1.821265    1
 1.748498    1
-1.964800    1
-1.762128    1
Name: count, Length: 100, dtype: int64


class
0    50
1    50
Name: count, dtype: int64

In [5]:
df.describe()

         feature1    feature2       class
count  100.000000  100.000000  100.000000
mean    -0.009348   -0.055507    0.500000
std      2.208348    2.024641    0.502519
min     -3.780303   -3.569145    0.000000
25%     -1.944888   -1.982278    0.000000
50%     -0.268907   -0.196039    0.500000
75%      2.035186    1.758542    1.000000
max      5.263112    3.280836    1.000000

In [29]:
class_value = df['class'].value_counts()
print(class_value)


if len(class_value) == 2:
    ratio = class_value.min() / class_value.max()
    print(f"Imbalance ratio: {ratio:.3f}")
    if ratio < 0.5:
        print("imbalanced.")
    else:
        print("balanced.")

class
0    50
1    50
Name: count, dtype: int64
Imbalance ratio: 1.000
balanced.

In [31]:
df

    feature1  feature2  class
0  -2.368256  0.605615      0
1  -2.460313  1.729759      0
2   1.292390 -2.291875      1
3  -3.780303 -1.534776      0
4   3.297534  1.185131      1
..       ...       ...    ...
95 -1.699185  2.220762      0
96  1.037832  2.521379      1
97  2.701200 -1.616977      1
98 -2.438428 -0.997694      0
99  1.523677 -1.762128      1

[100 rows x 3 columns]

In [32]:

from sklearn.preprocessing import MinMaxScaler



print(df.head())


X = df.drop(columns=['class'])  # Features
y = df['class']                 




minmax_scaler = MinMaxScaler()
X_minmax_scaled = minmax_scaler.fit_transform(X)

X_minmax_scaled_df = pd.DataFrame(X_minmax_scaled, columns=X.columns)


print("\nMin-Max Scaled Data")
print(X_minmax_scaled_df.head())

   feature1  feature2  class
0 -2.368256  0.605615      0
1 -2.460313  1.729759      0
2  1.292390 -2.291875      1
3 -3.780303 -1.534776      0
4  3.297534  1.185131      1

Min-Max Scaled Data
   feature1  feature2
0  0.156141  0.609456
1  0.145961  0.773565
2  0.560927  0.186463
3  0.000000  0.296989
4  0.782651  0.694057

In [9]:
from sklearn.model_selection import train_test_split
X=df.drop('class',axis=1)
Y=df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training features shape:", X_train.shape)
print("Test features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

Training features shape: (80, 2)
Test features shape: (20, 2)
Training labels shape: (80,)
Test labels shape: (20,)

In [12]:
from sklearn.svm import SVC
from sklearn.metrics import *

svm1=SVC()
svm1.fit(X_train,y_train)
pred_svm1=svm1.predict(X_test)
print(accuracy_score(pred_svm1,y_test))
print(classification_report(pred_svm1,y_test))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

In [34]:
from sklearn.tree import DecisionTreeClassifier
DT1=DecisionTreeClassifier()
DT1.fit(X_train,y_train)
pred_DT1=DT1.predict(X_test)
print(accuracy_score(pred_DT1,y_test))
print(classification_report(pred_DT1,y_test))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

In [17]:
conf_matrix_svm = confusion_matrix(y_test,pred_svm1)
conf_matrix_tree = confusion_matrix(y_test,pred_DT1)

In [19]:
print(conf_matrix_svm)

[[13  0]
 [ 0  7]]

In [20]:
print(conf_matrix_tree)

[[13  0]
 [ 0  7]]

In [23]:
print("SVM Accuracy:", accuracy_score(pred_svm1,y_test))
print("Decision Tree Accuracy:", accuracy_score(pred_DT1,y_test))

SVM Accuracy: 1.0
Decision Tree Accuracy: 1.0

In [22]:
results_df={"SVM":[accuracy_score(pred_svm1,y_test)],
            "Decision Tree":[accuracy_score(pred_DT1,y_test)]}
results_df=pd.DataFrame(results_df)
results_df

   SVM  Decision Tree
0  1.0            1.0